import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useSession, signIn } from "next-auth/react";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { data: session } = useSession();

  if (!session)
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="flex flex-1 min-h-screen">
          <button
            onClick={() => signIn("google")}
            className="m-auto px-4 py-2 bg-white text-black"
          >
            with google
          </button>
        </div>
      </>
    );
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>
        Hello, <b>{session?.user?.name}</b>
      </h2>
      <span className="px-2">{session?.user?.name}</span>
      <Image
        src={session?.user?.image}
        width={50}
        height={50}
        alt="Picture of the author"
      />
    </>
  );
}
